name       : openexr
version    : 2.3.0
homepage   : https://www.openexr.com/
release    : 8
source     :
    - https://github.com/openexr/openexr/releases/download/v2.3.0/openexr-2.3.0.tar.gz : fd6cb3a87f8c1a233be17b94c74799e6241d50fc5efd4df75c7a4b9cf4e25ea6
license    : BSD-3-Clause
component  : multimedia.library
summary    : A high dynamic-range image file format library
description: |
    A high dynamic-range image file format library
builddeps  :
    - pkgconfig(IlmBase)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
