name       : openexr
version    : 2.5.4
release    : 9
source     :
    - https://github.com/AcademySoftwareFoundation/openexr/archive/v2.5.4.tar.gz : dba19e9c6720c6f64fbc8b9d1867eaa75da6438109b941eefdc75ed141b6576d
homepage   : https://www.openexr.com/
license    : BSD-3-Clause
component  : multimedia.library
summary    : A high dynamic-range image file format library
description: |
    A high dynamic-range image file format library
builddeps  :
    - pkgconfig(IlmBase)
setup      : |
    %patch -p1 < $pkgfiles/dont-build-ilmbase-again.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
