name       : openexr
version    : 3.1.5
release    : 12
source     :
    - https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v3.1.5.tar.gz : 93925805c1fc4f8162b35f0ae109c4a75344e6decae5a240afdfce25f8a433ec
homepage   : https://www.openexr.com/
license    : BSD-3-Clause
component  : multimedia.library
summary    : A high dynamic-range image file format library
description: |
    OpenEXR provides the specification and reference implementation of the EXR file format, the professional-grade image storage format of the motion picture industry.

    The purpose of EXR format is to accurately and efficiently represent high-dynamic-range scene-linear image data and associated metadata, with strong support for multi-part, multi-channel use cases.

    OpenEXR is widely used in host application software where accuracy is critical, such as photorealistic rendering, texture access, image compositing, deep compositing, and DI.
builddeps  :
    - pkgconfig(Imath)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
