name       : openexr
version    : 2.2.0
release    : 1
source     :
    - http://download.savannah.nongnu.org/releases/openexr/openexr-2.2.0.tar.gz : 36a012f6c43213f840ce29a8b182700f6cf6b214bea0d5735594136b44914231
license    : BSD-3-Clause
summary    : A high dynamic-range image file format library
description: |
    A high dynamic-range image file format library
builddeps  :
    - pkgconfig(IlmBase)
clang      : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
