name       : openexr
version    : 2.2.1
homepage   : https://www.openexr.com/
release    : 6
source     :
    - http://download.savannah.nongnu.org/releases/openexr/openexr-2.2.1.tar.gz : 8f9a5af6131583404261931d9a5c83de0a425cb4b8b25ddab2b169fbf113aecd
license    : BSD-3-Clause
component  : multimedia.library
summary    : A high dynamic-range image file format library
description: |
    A high dynamic-range image file format library
builddeps  :
    - pkgconfig(IlmBase)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
